# Generated by Django 3.0.4 on 2020-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200624_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
